### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by CodingItWrong** [MelSumner/ember-component-patterns#2]
I reviewed the site as a whole and have a number of small pieces of feedback:

- Buttons:
	- You mention input type=submit, should input type=button also be mentioned?
	- “It should also be explicitly ensured that the image is not available to other machines”—as a developer when I say “other machines” I usually mean “computers running the code other than the one I’m on.” But of course the image needs be available to end users to display it. In a case like this others have said “assistive technologies”—there may be a better general phrase for it, but *something* in this area more specific than “other machines” can help with the misunderstanding I mentioned.
	- Antipatterns: in a future phrase it could be good to add an FAQ here, like reasons why developers push back and say that even despite all that they think they *do* still need to make a div clickable
- Checkboxes:
	- “an associated label input”—Is it typical to refer to <label> elements as “inputs”? I haven’t heard that. Since “input” has a technical meaning in forms, it might be best to avoid that word.
	- For the multiple-checkbox case, is a <fieldset> required/recommended? It could be good to mention whether or not that’s the case, to avoid misunderstandings.
	- This tri-state checkbox isn’t something I’m familiar with. Is there a page somewhere I can see an example of the “mixed” state?
	- “it should not be used in the place of common sense.”—I don’t follow this phrasing. And if this is saying to sometimes not use the helper, example could would be good—I assume it’s WIP.
- Text Fields
	- Consistency: this page has some detailed bullet points in the “introduction”, whereas the previous ones had just very general summary statements.
	- “Simply copying and pasting these code samples will not produce a complete result. “—in what sense are they not complete? Visually? UX?
	- “It should be noted that only the attribute is required.”—Since we’re talking about the `required` attribute, saying “the attribute is required” might cause confusion. Maybe add the clarification “It should noted that you do not need to provide a value for the attribute, just the attribute itself.”
	- I’ve heard of `type=number` but not of `pattern`; I wonder if there _are_ any browsers that support _pattern_ but not _type=number_ (Just an idle thought, don’t need to figure out for the page.)
	- Placeholder: the code snippet says “Zoey McEmber” but the image just shows “Zoey”
	- Attributes: why not use splattributes so you don’t need to explicitly pass them?
- Text Fields — Styling
	- Not everyone may know what Bootstrap is, could be good to link to it, or at least say “the Bootstrap CSS library”
- Radio Buttons
	- “it is preferred to plan out the component before building it.” This phrasing is unclear—does *everyone* prefer this? What if I don’t? Unless it gets too off-topic, it could be good to explain *why* the reader should prefer this, like “Planning out the component before building it can help avoid common pitfalls and rework” or something.
	- The radio group component example has `checked={{this.isSelected}}`, but doesn’t this mean that all of the radio buttons will check the same boolean component property to see if they’re checked or not? It seems like we need to compare the city name to a component property that stores the selected city name, or something similar with indices.
- Select Element
	- “While multiple selections can be allowed through the use of the multiple attribute, and most browsers will show a scrolling list box instead of a single line dropdown.” I think this is a sentence fragment; it looks like the previous sentence used to be a part of it, but was separated out (which is good). If you remove “While” then I think it works; this sentence states the positives of the multiple attribute as a complete thought, and the next sentence the warnings.
- Breadcrumbs
	- Could be good to show sample breadcrumbs rendered so users can visualize the dividers between them that CSS will be used to create

**Comment by MelSumner** [comment]
Thank you! I have incorporated this feedback into the project.
